### ISSUE TITLE
dca-rs reports missing file directory

### ISSUE THREAD

**Issue by RunitzTheDev** [nstafie/dca-rs#2]
So I'm trying to convert an mp3 file to dca-rs, using the x84 64-bit Windows dca-rs release, vers 0.1.0, and I realized it repeats this error message:

Error message:
![dca-rs info](https://cloud.githubusercontent.com/assets/12855077/16542887/8292d0ea-4070-11e6-897a-ed00795aaded.png)

Location of the .exe and .mp3 (moved after the picture, but same error; the audio file is in the same directory as the executable):
![dca-rs info2](https://cloud.githubusercontent.com/assets/12855077/16542899/b782f4ec-4070-11e6-91a5-c786880d3cbe.png)

Apparently, it's saying it couldn't find a file in the directory shown (C:\projects\dca-rs\target\....\out/main.rs:2918, which does not exist in my computer). Was I supposed to have something there? If so, what?

**Comment by nstafie** [comment]
Hi, it looks like you don't have ffmpeg installed on your system. Currently, dca-rs depends on the ffmpeg binary in order to decode the audio.

You can go here: https://ffmpeg.zeranoe.com/builds/ and download the applicable static build. Unzip it and you'll see a /bin/ folder. In there, you'll see `ffmpeg`, `ffplay` and `ffprobe` binaries. Move the ffmpeg and ffprobe binaries into your dca-rs folder and try again, it should work this time!

(I am working on removing that dependency, and the next version will no longer require ffmpeg binaries.)

**Comment by RunitzTheDev** [comment]
So it

**Comment by RunitzTheDev** [comment]
So the ffmpeg fixed that issue, but now I am getting a different issue:
![dca-rs error 2](https://cloud.githubusercontent.com/assets/12855077/16547309/123c6cb2-411e-11e6-8962-4604d0b0730f.png)


Any ideas on this error? I'll attach the mp3 just in case:
[boondocks_speech.zip](https://github.com/nstafie/dca-rs/files/345279/boondocks_speech.zip)

**Comment by nstafie** [comment]
Sorry I couldn't get back to you sooner, I've been extremely busy this week. 

That error happens because you're not redirecting your output to a file.
Try `dca-rs --raw --i boondocks_speech.mp3 > boondocks_speech.mp3`

**Comment by nstafie** [comment]
I assume it works? I'm closing this, feel free to open a new issue if you have any issues!
